export const TODOS = {
    ADD_TODO_BEGIN: "ADD_TODO_BEGIN",
    ADD_TODO_SUCCESS: "ADD_TODO_SUCCESS",

    DELETE_TODO_BEGIN: "DELETE_TODO_BEGIN",
    DELETE_TODO_SUCCESS: "DELETE_TODO_SUCCESS",

    POPULATE_TODOS_BEGIN: "POPULATE_TODOS_BEGIN",
    POPULATE_TODOS_SUCCESS: "POPULATE_TODOS_SUCCESS",
    
}